name: Linting
on:
  push:
  pull_request:
  workflow_dispatch:
jobs:
  lint-vcf-merge:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Linting for vcf_merge
        working-directory: general_pipelines/workflows/vcf_merge
        run: |
          python -m pip install snakemake pandas pybedtools
          snakemake --lint --cores 1
