name: Linting
on:
  push:
  pull_request:
  workflow_dispatch:
jobs:
  lint-vcf-merge:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Linting for vcf_merge
        working-directory: pipelines/vcf_merge
        run: |
          python -m pip install snakemake pandas pybedtools
          snakemake --lint --cores 1
  summarize-flagger-output:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Linting for summarize_flagger_output
        working-directory: pipelines/summarize_flagger_output
        run: |
          python -m pip install snakemake pandas
          snakemake --lint --cores 1
