name: snakemake-dry-runs
# Validate Snakefiles by doing a dry run (snakemake -n)
# to check that syntax/ DAG is correct
on:
  push:
  pull_request:
  workflow_dispatch:
jobs:  # Add dry run jobs for other workflows
  dry-run-vcf-merge:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11.7'
      - name: Snakemake dry run for vcf_merge
        # Directory that has Snakefile and config
        working-directory: pipelines/vcf_merge
        # Install dependencies and dry run
        run: |
          python --version
          python -m pip install snakemake==8.1.2 pandas pybedtools
          snakemake -n --cores 1 --configfile .test/config.yaml
  dry-run-summarize-flagger_output:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Snakemake dry run for summarize_flagger_output
        # Directory that has Snakefile and config
        working-directory: pipelines/summarize_flagger_output
        # Install dependencies and dry run
        run: |
          python -m pip install snakemake pandas
          snakemake -n --cores 1 --configfile .test/config.yaml
  dry-run-assembly_eval:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Snakemake dry run for assembly_eval
        # Directory that has Snakefile and config
        working-directory: pipelines/assembly_eval
        # Install dependencies and dry run
        run: |
          python -m pip install snakemake pandas pysam Bio
          snakemake -n --cores 1 --configfile .test/config.yaml
