name: snakemake-dry-runs
# Validate Snakefiles by doing a dry run (snakemake -n)
# to check that syntax/ DAG is correct
on:
  push:
  pull_request:
  workflow_dispatch:
jobs:  # Add dry run jobs for other workflows
  dry-run-vcf-merge:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Snakemake dry run for vcf_merge
        # Directory that has Snakefile and config
        working-directory: general_pipelines/workflows/vcf_merge
        # Install dependencies and dry run
        run: |
          python -m pip install snakemake pandas pybedtools
          snakemake -n --cores 1
  dry-run-summarize-flagger_output:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v4
        - name: Snakemake dry run for summarize_flagger_output
        # Directory that has Snakefile and config
        working-directory: general_pipelines/workflows/summarize_flagger_output
        # Install dependencies and dry run
        run: |
          python -m pip install snakemake pandas
          snakemake -n --cores 1