name: snakemake-dry-runs
# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
  pull_request:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  snakemake-dry-runs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: env_CI
          environment-file: env_CI.yml
          auto-activate-base: false
      - run: |
          conda info
          conda list

      - name: Snakemake dry run for vcf_merge
        uses: snakemake/snakemake-github-action@v1.25.1
        with:
          directory: general_pipelines/workflows/vcf_merge
          snakefile: general_pipelines/workflows/vcf_merge/Snakefile
          args: "-n --cores 1 --use-conda --conda-cleanup-pkgs cache"