name: snakemake-dry-runs

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  snakemake-dry-runs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Snakemake dry run for vcf_merge
        working-directory: general_pipelines/workflows/vcf_merge
        run: |
          python -m pip install snakemake pandas pybedtools
          snakemake -n --cores 1