name: snakemake-dry-runs
# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
  pull_request:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  snakemake-dry-runs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      #- uses: actions/setup-python@v4
      #  with:
      #    python-version: '3.7.1'
      - name: Install dependencies
        run: |
          eval "$(conda shell.bash hook)"
          conda create -n "envCI" python=3.7.1
          conda install -c bioconda -n envCI pybedtools
          conda env list
          conda activate envCI
          conda info
          conda list
          python -m pip install snakemake
      - name: Snakemake dry run for vcf_merge
        run: |
          snakemake -s general_pipelines/workflows/vcf_merge/Snakefile -n --cores 1 --use-envmodules --use-conda