name: snakemake-dry-runs
# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
  pull_request:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  snakemake-dry-runs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Snakemake dry run for vcf_merge
        run: |
          /usr/bin/python -m pip install snakemake pandas pybedtools
          snakemake -s general_pipelines/workflows/vcf_merge/Snakefile --configfile general_pipelines/workflows/vcf_merge/config/config.yaml -n --cores 1 --use-envmodules